#!/usr/bin/python
#
# this program generate code for javascript to be used in google map
# (html)
# 
# the input of this program is the html files generated by ip2html
# 
import sys
import os
import re
camcount = 0
filelist = os.listdir(".")
lat = 0
lon = 0
for filename in filelist:
    match = re.search("html", filename)
    if (match):
        fptr = open(filename, 'r')
        for oneline in fptr:
            latmatch = re.search("Latitude:\s*([\d\.]+)\s*\(", oneline)
            if (latmatch):
                # print oneline
                # print latmatch.group(1)
                lat = latmatch.group(1)
            lonmatch = re.search("Longitude:\s*([\-\d\.]+)\s*\(", oneline)
            if (lonmatch):
                # print oneline
                # print lonmatch.group(1)
                lon = lonmatch.group(1)
            imgmatch = re.search("img.*src=(\".*?\")>", oneline)
            if (imgmatch):
                img = imgmatch.group(1)
                print "camloc[" + str(camcount) + "] = new google.maps.LatLng("  + str(lat) + "," + str(lon) + ");"
                print "camimg[" + str(camcount) + "] = " + img 
                camcount = camcount + 1
        fptr.close()
